/* AUTO-GENERATED by scripts/gen-nav-manifest.ts */
import type { NavManifest } from "@/types/nav";
export const NAV_MANIFEST: NavManifest = [
  {
    "meta": {
      "includeInNav": true,
      "priority": 99,
      "title": "Portfolio"
    },
    "path": "/portfolio"
  },
  {
    "meta": {
      "includeInNav": true,
      "priority": 95,
      "title": "Leaderboard"
    },
    "path": "/leaderboard"
  },
  {
    "meta": {
      "includeInNav": true,
      "priority": 90,
      "title": "Market"
    },
    "path": "/market"
  }
] as const;
